### ISSUE TITLE
Code does not match with paper

### ISSUE THREAD

**Issue by ixsluo** [hoffmannjordan/Encoding-Decoding-3D-Crystals#1]
Hello Dr. Hoffnann,

I have a question that why the convolution layers used in the VAE in your code do not match with the descriptions in your paper.

There are 5 convolution layers in each encoder and decoder in code, but 4 in the supplemental information of the paper.

And I could not sent email to `echo ude.dravrah.g@nnamffohj|rev`, is it correct?

**Comment by hoffmannjordan** [comment]
Sorry-- I hadn't seen. If my email response didn't clear things up, feel free to raise a new issue or reopen this one!
